github: [metadata]
brief-intro: C++ Developer
url: "https://dalzhim.github.io"

permalink: /:year/:month/:day/:title/

twitter_username: Gab_AL_
github_username: Dalzhim

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

category_dir: category/
tag_dir: tag/

excerpt_separator: "\n\n"

gems: [jekyll-paginate]
paginate: 3
